---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-app-service
  namespace: minecraft-application
spec:
  type: "NodePort"
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32005
      protocol: TCP
  selector:
    run: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-app
  namespace: minecraft-application
spec:
  selector:
    matchLabels:
      run: minecraft-app
  replicas: 2
  template:
    metadata:
      labels:
        run: minecraft-app
    spec:
      containers:
      - name: minecraft-app
        image: 568170370118.dkr.ecr.us-east-1.amazonaws.com/minecraft:replaceImageTag
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi

      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-app-ingress
  namespace: minecraft-application
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: 200,302
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    run: app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80


      
