apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft-app
  template:
    metadata:
      labels:
        app: minecraft-app
    spec:
      containers:
      - name: minecraft-app
        image: dappyplay4u/minecraft:latest
        ports:
        - containerPort: 8080